service: imageUploadDemo

provider:
  name: aws
  runtime: nodejs8.10
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::teachosm-project-pics/*"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::lambda-libreoffice-teachosm-demo/*"


# Expose function to public API for POST requests.
functions:
  requestUploadURL_pics:
    handler: handler.requestUploadURL_pics
    events:
      - http:
          path: requestUploadURL_pics
          method: post
          cors: true
  requestUploadURL_content:
    handler: handler.requestUploadURL_content
    events:
      - http:
          path: requestUploadURL_content
          method: post
          cors: true

# Give service access to the specific S3 bucket.
# resources:
#   Resources:
#     UploadBucket:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: teachosm-project-pics
#         AccessControl: PublicRead
#         CorsConfiguration:
#           CorsRules:
#           - AllowedMethods:
#             - GET
#             - PUT
#             - POST
#             - HEAD
#             AllowedOrigins:
#             - "*"
#             AllowedHeaders:
#             - "*"
