# serverless.yml

service: convert-post-request-to-yaml

plugins:
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  bucket: teachosm-project-posts-deployed

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  deploymentBucket:
    name: convert-post-request-to-yaml-deploy
  region: us-east-1
  # Provide permissions for this service to manipulate S3.
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::teachosm-project-posts-deployed/*"

functions:
  app:
    handler: index.handler
    events:
      - http: 
            path: /
            method: any
      - http: 
            path: '{proxy+}'
            method: any
  getPost:
    handler: index.handler
    events:
      - http: 
            path: '/posts/{proxy+}'
            method: get
  createPost:
    handler: index.handler
    events:
      - http: 
            path: /posts
            method: post
            cors: true




