service: aws-commit-to-github

frameworkVersion: ">=1.1.0"

plugins:
  - serverless-offline-direct-lambda
  - serverless-offline

#custom:
#  bucket: teachosm-project-posts

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"

# s3 bucket cannot be created beforehand, due to cloudformation limitation
functions:
  githubCommit:
    handler: index.handler
    #events:
    #  - s3:
    #      bucket: ${self:custom.bucket}
    #      event: s3:ObjectCreated:*
